[build]
  command = "npm run build"
  publish = "dist"
  ignore = "tsc"

[build.environment]
  NODE_VERSION = "18"  # Usa la misma versión que localmente
  CI = "false"         # Desactiva el modo CI estricto